export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const DASHBOARD_INFOS_START =  'DASHBOARD_INFOS_START';
export const DASHBOARD_INFOS_SUCCESS = 'DASHBOARD_INFOS_SUCCESS';
export const DASHBOARD_INFOS_FAIL = 'DASHBOARD_INFOS_FAIL';
export const DASHBOARD_INFOS_INIT =  'DASHBOARD_INFOS_INIT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

